apiVersion: apps/v1
kind: Deployment
metadata:
  name: form-recognizer-layout
  labels:
    app: form-recognizer-layout-deployment
spec:
  selector:
    matchLabels:
      app: form-recognizer-layout-app
  replicas: 1
  template:
    metadata:
      labels:
        app: form-recognizer-layout-app
    spec:
      containers:
        - name: cognitive-services-form-recognizer-layout
          image: mcr.microsoft.com/azure-cognitive-services/form-recognizer/layout
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: 3000m
              memory: 16Gi
          env:
            - name: EULA
              value: accept
            - name: billing
              value: https://canadacentral.api.cognitive.microsoft.com/ # Localize - note that this can also be in the form https://canadacentral.api.cognitive.microsoft.com
            - name: apikey
              value: daff... # Localize
            - name: HTTP_PROXY
              value: http://<your-proxy>.com:XXXX # Localize
            - name: EnableSyncNTPServer
              value: "false"
          livenessProbe:
            httpGet:
              path: /ContainerLiveness
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 20
          args:
            - "Logging__Console__LogLevel__Default=Debug"
---
apiVersion: v1
kind: Service
metadata:
  name: raki-cognitive-form-recognizer-layout
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5000
  selector:
    app: form-recognizer-layout-app
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: raki-cognitive-form-recognizer-layout-route
spec:
  host: raki-cognitive-form-recognizer-layout.apps.ocp-env.your-route.com
  to:
    kind: Service
    name: raki-cognitive-form-recognizer-layout
    weight: 100
  port:
    targetPort: 5000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
