apiVersion: apps/v1
kind: Deployment
metadata:
  name: read
  labels:
    app: read-deployment
spec:
  selector:
    matchLabels:
      app: read-app
  replicas: 1
  template:
    metadata:
      labels:
        app: read-app
    spec:
      containers:
        - name: cognitive-services-read
          image: mcr.microsoft.com/azure-cognitive-services/vision/read:3.2
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 5Gi
          env:
            - name: EULA
              value: accept
            - name: billing
              value: https://canadacentral.api.cognitive.microsoft.com/ # Localize - note that this can also be in the form https://canadacentral.api.cognitive.microsoft.com
            - name: apikey
              value: eb1... # Localize
            - name: HTTP_PROXY
              value: http://your-http-proxy.com # Localize
          livenessProbe:
            httpGet:
              path: /ContainerLiveness
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: raki-cognitive-read
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 443
      targetPort: 5000
  selector:
    app: read-app
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: raki-cognitive-read-route
spec:
  host: raki-cognitive-read.apps.your-domain.com
  to:
    kind: Service
    name: raki-cognitive-read
    weight: 100
  port:
    targetPort: 5000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None