apiVersion: apps/v1
kind: Deployment
metadata:
  name: read
  labels:
    app: read-deployment
spec:
  selector:
    matchLabels:
      app: read-app
  replicas: 3
  template:
    metadata:
      labels:
        app: read-app
    spec:
      containers:
        - name: cognitive-services-read
          image: mcr.microsoft.com/azure-cognitive-services/vision/read
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 100m
              memory: 1Gi
            limits:
              cpu: 300m
              memory: 2Gi
          env:
            - name: EULA
              value: accept
            - name: billing
              value: https://eastus.api.cognitive.microsoft.com
            - name: apikey
              value: #58abacb643034607896304d75....
            - name: Storage__ObjectStore__AzureBlob__ConnectionString
              value: #DefaultEndpointsProtocol=https;AccountName=...;AccountKey=...;EndpointSuffix=core.windows.net
            - name: Queue__Azure__ConnectionString
              value: #DefaultEndpointsProtocol=https;AccountName=...;AccountKey=...;EndpointSuffix=core.windows.net
          livenessProbe:
            httpGet:
              path: /ContainerLiveness
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 60
            timeoutSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: azure-cognitive-service-read
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: read-app
